name: Release
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install dependencies
        run: npm ci
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npm run commitlint -- --from=origin/main --to=HEAD
      - name: Lint & check types
        run: npm run check
      - name: Test
        run: npx vitest run

  Release:
    needs: [Test]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
